# Generated by Django 5.2.14 on 2026-05-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_healthdata_alter_meal_id_alter_sleep_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthdata',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='sleep',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='workout',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
