# Generated by Django 5.2.14 on 2026-05-20 06:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_remove_healthdata_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
